### ISSUE TITLE
Add batch accepting/rejecting for iRODS delete requests

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1340]
I discussed this with @holtgrewe and it would make sense to allow batch accepting or rejecting of iRODS delete requests, with some fallbacks.

## Spec

- Add checkboxes for delete requests
- Replace `Create Request` button with a `Request Operations` dropdown with the following options:
    * Create Request
    * Accept Selected
    * Reject Selected
- Make "Accept Selected" and "Reject Selected" options disabled, if no checkboxes are selected
    * This has to be done in JQuery of course
- Modify `IrodsRequestAcceptView` and `IrodsRequestRejecttView` to accept a list of objects
    * I believe `IrodsRequestAcceptView` should be changed from `FormView` to `View` similar to `IrodsRequestRejecttView`.. But whatever works is ok :)
- Make sure to list all files to be deleted from each request in the accept confirmation view
- Add tests
- Update docs to note that accepting/rejecting multiple requests is possible this way
- **HINT:** Check filesfolders in SODAR Core for an example how we have done this before
    * ..at least regarding the UI & JQuery side
    * The batch delete/move view itself is quite messy and is not probably the best example :)

**Comment by xiamaz** [comment]
This is also something that is useful for CADS. Is it currently already possible to issue delete requests via API? Accepting via API is not necessary.

We need to delete all files associated with a single assay entry, if this is already something possible without issuing a single deletion request for each individual file, please let me know.

**Comment by mikkonie** [comment]
Right now it's possible to create delete requests for single files or collections. As for now, issuing requests via API is not possible, but this can definitely be added in the future.

**Comment by mikkonie** [comment]
Done by @gromdimon.
