### ISSUE TITLE
Manual link in irodsinfo points to old manual URL

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/sodar-server#1442]
**Issue**
Broken link in 'iRODS Info' page; link to manual is pointing to https://sodar.bihealth.org/manual (Page Not Found) instead of  https://sodar-server.readthedocs.io/en/latest/ (?)

![grafik](https://user-images.githubusercontent.com/22077515/178671519-5632d9b6-acdd-441f-9c71-e5636ad757d5.png)

**Comment by mikkonie** [comment]
`irodsinfo` is a SODAR app, transferring this into the correct repository.

**Comment by mikkonie** [comment]
Fixed.
