### ISSUE TITLE
Hide irrelevant fields in sheet template forms

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1443]
@eudesbarbosa pointed out a thing I completely missed before: in the UI we are showing fields which are not expected to be edited, and which do not affect anything if edited. Example of this is the `lib_kits` field, which simply provides options for `lib_kit`.

The initial simple solution is simply to add a "black list" for templates, as we have a fixed set of them and can tell which ones have which fields.

Once we allow for inclusion of user-made templates, we should denote such fields in the templates with a special syntax. @holtgrewe suggested e.g. prefixing them as `__field_name`. I will add appropriate issues once I'm doing the separation of templates from cubi-tk.

Since the simple solution is trivial to implement, I'll squeeze this to the publication milestone v0.11.3.

**Comment by mikkonie** [comment]
Done.

**Comment by sellth** [comment]
Prefixing them as `__field_name` is the official cookiecutter way of defining private/hidden variables. They are in fact already ignored by SODAR in the "Create from template" form (could not find out why though). Converting these fields to private variables should be the long-term fix here imo.

https://cookiecutter.readthedocs.io/en/stable/advanced/private_variables.html
