### ISSUE TITLE
Add project-based setting to select genome for IGV

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1478]
This is a case which has been raised a few times by @ericblanc20. One possible way to do this is to enable iRODS metadata based tagging as described in #1321. Adding this ticket for the use case itself in case we decide on some other approach.

Another possibility would be to implement a faster approach where we would simply look into paths, such as `*/GRCh38/*` and select based on some variable.

Comments are welcome.

**Comment by mikkonie** [comment]
List of possible genome version names from Eric:

- GRCh37
- hs37d5
- b37
- hs19
- GRCh38
- hs38
- GRCh38.d1.vd1

**Comment by ericblanc20** [comment]
Correction: the last one reads: `GRCh38.d1.vd1` (the [GDC reference genome](https://gdc.cancer.gov/about-data/gdc-data-processing/gdc-reference-files), containing viral sequences commonly found in cancer samples, and decoys)

**Comment by mikkonie** [comment]
This has been raised again. I will see about prioritizing it.

**Question:** Would it be enough to have a project-level selection? That should be quite trivial to implement with existing things.

**Comment by mikkonie** [comment]
At Benedikt's request, I'm adding a project-level setting for this for now. If we need to support multiple genomes within one project, we'll have to implement that additional functionality later.

**Comment by mikkonie** [comment]
Project-level selecting of IGV session genome done.

For a more complicated implementation supporting multiple genomes within the same project/study, we'll have to get together for some planning and spec it out.
