### ISSUE TITLE
Add warning users of inconsistent data in sheet editor

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1494]
Add editor feature to check for existing collections in iRODS when renaming libraries.

- IF editing cell value
- AND cell type is material name
- THEN check
    * **TODO:** Check if we can look directly into cached data or if we have to add new assay plugin functionality
- IF file(s) exist THEN display alert confirming edit before proceeding

**Comment by holtgrewe** [comment]
SODAR already does a good job keeping the ISA-tab itself consistent. You cannot just rename a material, in particular sample, and get disconnected DAGs as far as I can see.

However, an important area that we are lacking is the connection between assay results and the irods file storage. When renaming the result of DNA sequencing, e.g., from `A-N1-DNA1-WES1` to `B-N1-DNA1-WES1` then we might end up with an "orphan folder" for `A-...` and `B-...` is missing. We should (a) show users warnings about existing orphan folders and (b) warn them when renaming samples that already have a connecting folder. We should consider (c) looking at landing zones and ensure that they have a corresponding sample at the point in time when we run validation.

Of course, this will exclude the "MiscFiles" etc.

**Comment by mikkonie** [comment]
Done.
