### ISSUE TITLE
IGV Tracks per default are blue

### ISSUE THREAD

**Issue by xiamaz** [bihealth/sodar-server#1514]
### Describe the Bug

Currently loading an IGV session from SODAR will show blue BAM tracks. This is bad, as C nucleotides are also blue and makes writing very difficult to read:

![image](https://user-images.githubusercontent.com/3340720/199191239-2aa8c2ff-1eb4-4624-a6ed-c6d42c3fb177.png)

### How to Reproduce

Open IGV session for a SODAR family sample with available BAM tracks. Zoom in until alignments become visible.

### Expected Behavior

The default color of BAM tracks should ensure legbility of text, such as using a neutral gray color:

![image](https://user-images.githubusercontent.com/3340720/199191955-a428af8c-de77-4c7e-8514-445ddf728044.png)

### Proposed fix

Change the default color in the IGV session to a more sane variant.

**Comment by xiamaz** [comment]
https://github.com/bihealth/sodar-server/blob/2790b23832443df2ded837b617a00984417448a6/samplesheets/studyapps/utils.py#L173

**Comment by mikkonie** [comment]
Thank you for reporting, I will look into this.

**Comment by xiamaz** [comment]
Thanks, just changing the color of the BAM track should amend the issue.

**Comment by mikkonie** [comment]
Thanks for the pull request, please change the target branch to `dev` and I can merge.

**Comment by mikkonie** [comment]
Thanks a lot, pull request merged. I'll deploy these latest changes in production shortly.
