### ISSUE TITLE
Update url patterns to use `path`

### ISSUE THREAD

**Issue by gromdimon** [bihealth/sodar-server#1631]
### Problem

As it was implemented in sodar-core [issue](https://github.com/bihealth/sodar-core/issues/1116) # 1116 we should upgrade regex patterns in urls in sodar.

### !!!Copy-paste from sodar-core issue!!!
- In all apps, update `regex` URLs to use `route`
  * As an example, `regex=r'^update/(?P<project>[0-9a-f-]+)$'` would become `route='update/<uuid:project>'`.
  * Preserving the original kwarg names is critical, as those are used by `ProjectAccessMixin` to determine perms.
  * There might be some 
- **Exception:** Leave URLs in `example_project_app` as is, because in there we ensure the working of both regex and path URLs
- Running existing tests should catch any problems with forming URLs in case there's a mistake or typo.
  * No new tests should be required.
- Docs and examples within should be updated to reflect that the recommended way of setting URLs is using `route`, but `regex` also works.
  * See [dev_project_app.rst](https://sodar-core.readthedocs.io/en/dev/dev_project_app.html#url-keyword-arguments)

**Comment by mikkonie** [comment]
Done by @gromdimon.
