### ISSUE TITLE
Calculate missing iRODS checksums for files on landing zone validate/move

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1634]
Something also discussed with @sellth: if possible, it would make sense to automatically calculate missing iRODS checksums for files upon zone validation and moving. This should be easily doable with `chksum()` in the python-irodsclient. Not sure why we are not already doing this, tbh.

To think of it, implementing this would also make #1633 kind of pointless..

**TODO:** Full spec

**Comment by sellth** [comment]
This would improve UX quite a lot as it enables (small?) file uploads via Davrods. WebDAV links can be mounted by many file managers (Windows, Mac, Gnome) and provide easy access to SODAR LZs. Currently, not being able to trigger remote checksum computation is blocking this route.

Who would benefit from this?
- Users outside of the MDC/Charité/BIH-Network (i. e. the [Blüthgen group](https://www.sys-bio.net/), but possibly others) . Currently only two step uploads via HPC available.
- Users with a preference for GUI applications.
- Windows users in general.

**Comment by mikkonie** [comment]
Done.
