### ISSUE TITLE
Add a new samplesheet assay plugin for mass cytometry data

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1642]
Mass cytometry data is quite similar to scRNA-seq data, but differs in the details. For handling these kind of datasets, a dedicated assayapp is needed.

## Requirements
1. Multiple samples are measured as multiplexed pools, so SODAR should point all of these samples to one iRODS collection using the "last material node" logic of the RNA_sequencing plugin.
2. Various protocol parameters are too complex for direct inclusion into the ISA-tab and need to be linked from the MiscFiles collection. The plugin should provide auto-linking of these resources similar to the ms_meta plugin.
3. Various protocols generate report files which should be linked from the respective multiplexed "run" collection.

**Comment by mikkonie** [comment]
Done by @sellth and merged.
