### ISSUE TITLE
Sheet upload widget only allows single file

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1670]
Prior to this update it was possible to select multiple files in the upload file dialogue of the "Replace Current Sample Sheets with ISA-Tab" window. Currently only one file can be selected.

This seems due to changes in bd3fec4a52d24b5d716c2207a1a4183853b02604. The new argument *allow_multiple_selected* is not being properly handled by Django i. e. replaced with the HTML "multiple" attribute.

![grafik](https://github.com/bihealth/sodar-server/assets/29800411/6cc0925f-13ca-44a7-86e6-9f60c7305322)

Replacing *allow_multiple_selected* with *multiple=""* in the browser rescues this phenotype.

### System Information
 - Ubuntu 22.04
 - Firefox 113

**Comment by mikkonie** [comment]
This was changed according to the Django changelog guide to prevent the entire site from crashing. I'll see how to enable this. Meanwhile, the workaround is to upload sample sheets as a zip archive.

**Comment by mikkonie** [comment]
Fixed.
