### ISSUE TITLE
ISA-tab import fails when no material present in assay

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1671]
Importing ISA-tabs where Sample Name is the only material in the assay file fails with the following message:

`No materials in assay "a_assay_name.txt": Importing sheets with tables containing zero lines is currently not supported.`

This is not an Altamisa exception. Altamisa parses this ISA-tab without any error messages.

### Expected Behavior

ISA-tabs with only Sample Name as a material in the assay sheet should be imported. Workaround: Add an empty material or data column to ISA-tab.

**Comment by mikkonie** [comment]
Not a bug, expected behaviour. Empty assays will be supported in the future when creating new studies and assays in the editor is added. If not there, I will add a note about it in the manual.

**Comment by sellth** [comment]
Sorry, should have clarified. Sample Name is not the only node in this assay. 

This graph fails: Sample Name > Process > Process > Process
This graph works: Sample Name > Process > Process > (any Material) > Process

There are also rows filled out. This behaviour was unexpected, at least for me. 

While this may not be ISA compliant, it works in SODAR imo, because the data collection links created for samplesheets provide a sort of final "Data material" node for the assay.
