### ISSUE TITLE
Add irodsinfo REST API endpoint to retrieve iRODS configuration

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1685]
This would enable external tools such as cubi-tk to automatically fetch a valid iRODS configuration if SODAR API access was already established. Not relying on the user manually downloading `irods_environment.json` into the right location improves UX during onboarding of new users/machines.

related: bihealth/sodar-cli/issues/6

**Comment by mikkonie** [comment]
The API entry point should be in the `irodsinfo` app, not `samplesheets`. Other than that, this is a good idea. I'll write up a complete spec and we can include this in v0.14.

**Comment by mikkonie** [comment]
## Spec

- Add REST API endpoint to `irodsinfo.views_api`
    * Name = `IrodsConfigRetrieveAPIView`
    * Method = `GET`
    * Permission class = `IsAuthenticated`
    * Return user iRODS config as JSON
       + Format: `{'irods_environment': {irods-env-goes-here}}`
- Refactor config generating in `IrodsConfigView` into a mixin
    * Both views should use the same mixin to generate the config
- Let's ignore the certificate part for now, as it's not currently required by the client in our iRODS server implementation
- Add permission and view tests for the API view
- Add `irodsinfo` REST API docs to manual

**Comment by mikkonie** [comment]
Done by @gromdimon.
