### ISSUE TITLE
Empty string in sheet template field choices displays empty options dialogue

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1700]
When an ISA-tab template includes a choice variable with one of the items being an empty string, the drop-down menu in SODAR's Samplesheets > Create from template for that variable is empty i. e. displays no items at all. This can be seen with the current version of the MS Metabolomics Biocrates kit ISA-tab template. Variables:

- Biocrates metidq version
- Metaquac version

Expected behaviour: Drop-down menu displays empty line for empty string choices.

**Comment by mikkonie** [comment]
Interesting, maybe this is some Django feature. I'll take a look later this week.

**Comment by sellth** [comment]
I've added a PR that fixes this behaviour: #1701

**Comment by mikkonie** [comment]
Fixed by @sellth.
