### ISSUE TITLE
Add support for cookiecutter prompts in sheet templates

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1726]
[Cookiecutter v2.2.0](https://github.com/cookiecutter/cookiecutter/releases/tag/2.2.1) added the possibility to define custom messages per variable instead of the default `<variable_name> [default]:` prompt. SODAR should check for the special `__prompts__` config field and use these strings as form labels in the "Create from template" screen.

https://cookiecutter.readthedocs.io/en/stable/advanced/human_readable_prompts.html

**Comment by mikkonie** [comment]
Sounds good and most likely will be trivial to implement.

**Comment by mikkonie** [comment]
@sellth, please ping me when there are templates in the cubi-isa-templates main branch using this feature and I'll add support to SODAR.

**Comment by sellth** [comment]
@mikkonie once [this PR](https://github.com/bihealth/cubi-isa-templates/pull/15) lands there will be a template using this feature. The custom prompts also resolve the concerns @Nicolai-vKuegelgen had in bihealth/cubi-isa-templates#13.

**Comment by mikkonie** [comment]
Done.
