### ISSUE TITLE
Hide fields starting with underscore from sheet templates

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1733]
Discussed with @sellth. The [cubi-isa-templates]() repo is going to be updated to name all fields not expected to be filled by the user with an underscore, e.g. `_library_types`.

Updating to this means we can get rid of `HIDDEN_SHEET_TEMPLATE_FIELDS` and simply filter by filed name.

`__output_dir` is currently an exception, but it's in fact only used internally within SODAR to denote the directory under the ISA-Tab archive where the files should go. We can replace this with a form field of our own.

This should be done together with #1726.

**Comment by sellth** [comment]
Templates updated

**Comment by mikkonie** [comment]
Done. The use of `__output_dir` was left as is, because a workaround for that would be.. well, a workaround.
