### ISSUE TITLE
Allow boolean variables in sheet templates 

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1757]
### Problem

Cookiecutter v2.2+ allows for boolean-type variables. SODAR does currently not recognise those as valid form fields and omits them in the "Create from template" dialogue.

### Solution

Boolean variables should be parsed and treated as multiple choice for simplicity.

### Additional Context

- https://cookiecutter.readthedocs.io/en/stable/advanced/boolean_variables.html
- relevant for this upcoming template: https://github.com/bihealth/cubi-isa-templates/pull/23
- Generally useful feature which would allow for more flexibility in templates.

**Comment by mikkonie** [comment]
I have a work branch up with this change and a dependency to the pr commit, it seems to work just fine. See the commit mentioned above.

Let me know when this is merged and I will update the dependency and merge this into dev.

**Comment by mikkonie** [comment]
Note to self: this initial implementation apparently will not work with the `tumor_normal_dna` and `tumor_normal_triplets` templates, as they require the hack in `save()` which I just removed:

```
if 'is_triplet' in self.sheet_tpl.configuration:
    extra_context['is_triplet'] = self.sheet_tpl.configuration[
        'is_triplet'
    ]
```

However, with the cancer template (which actually has `is_triplet` as a boolean variable), this can not be used. Either we have to 1) fix the other templates to not require this hack, or 2) limit the hack only to be used with specific templates. I'd of course be in favour of the former approach, if feasible.

**Comment by sellth** [comment]
FYI we're still discussing changes to the new _somatic_ template relying on this feature. Expectation is that it'll take another week or two as there is not much pressure. The final merge will however also remove _tumor_normal_dna_ and _tumor_normal_triplets_.

**Comment by mikkonie** [comment]
Done.
