### ISSUE TITLE
Ontology URLs not encoded if passed as query in wrapper URL template

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1762]
### Problem

Certain ontologies include the hash symbol in their term IDs, which is a problem because it's a special symbol in HTML. Ergo, when using these terms in SODAR, external linking does not work. This is the case for the [National Cancer Institute Thesaurus (NCIT)](https://bioportal.bioontology.org/ontologies/NCIT) ontology, but possibly others as well.

Example: https://bioportal.bioontology.org/ontologies/NCIT/?p=classes&conceptid=http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C98283

### Solution

Auto-escape hash symbols in ontology IDs to `%23`

Working: https://bioportal.bioontology.org/ontologies/NCIT/?p=classes&conceptid=http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl%23C98283

**Comment by mikkonie** [comment]
Good catch, this should be a very simple one to implement.

**Comment by mikkonie** [comment]
Fixed.

**Comment by sellth** [comment]
Works like a charm, thank you. One small thing: `encodeURIComponent()` breaks the current workaround for the initial bug i.e. replacing # with %23. Now the % character is substituted with %25, resulting in %2523. 

AFAIK I was the only one using this workaround though, but also is part of the `somatic` and `mass_cytometry` templates. Will fix.
