### ISSUE TITLE
README preview <> result disparity

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1764]
### Describe the Bug

When composing a project README, beneath the input textbox a preview is rendered in real time. 
- Single newlines are rendered as newlines
- Forced line breaks (`\`) are not rendered
-  _http://_ strings are auto-converted to clickable links. 

However, this does not reflect the final rendering after saving. In the project overview window:
- Single newlines are rendered as space (no line break)
- Forced line breaks are rendered as newlines.
- _http://_ strings are not rendered as clickable links

### Expected Behavior

Editor preview and final rendering should agree on what Markdown features to support. My preference is with how the preview box handles Markdown input.

**Comment by mikkonie** [comment]
Issue raised in the wrong project, this is a SODAR Core feature. Furthermore, this is rendered by a 3rd party component so feel free to submit a bug report to them.
