### ISSUE TITLE
Button to maximise samplesheet tables

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1778]
Default samplesheet tables are quite limited in the amount of rows displayed. This can be extended in user settings, but that is probably not an obvious place to put such a setting.

A "Maximize this table to fill the viewport" button next to samplesheet tables would be pretty useful, I think.

**Comment by mikkonie** [comment]
Dupe of #654. That issue hasn't been touched in a while but feel free to comment there. I agree it would be very useful.
