### ISSUE TITLE
Add list value support for missing fields

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1789]
### Describe the Bug
Inputting a semicolon separated list in any `Characteristics`, `Comment`, `Parameter`, or `Factor` field results in AltamISA creating a list value for that object. In case of Characteristics and Parameters these lists are handled by SODAR without any problems. Lists in special protocol parameter `Performer` fields however result in raw Python list notation being rendered (i.e. `['Person 1', 'Person 2']`). Entering semicolons in `Comment` fields results in an exception and a no longer usable ISA-tab.

### How to Reproduce
1. Create a new SODAR project.
2. Edit samplesheets.
3. Add semicolon-separated values in Comment and Performer fields.

### Expected Behavior
Lists should be rendered in a similar way to `Characteristics` and `Parameter` fields. As `Comments` and `Performer` fields cannot be differentiated from "normal" characteristics and parameters in the SODAR samplesheet editor, this case needs to be handled. Putting multiple performers for a `Process` is actually a useful option when more than one person should be credited.

### Screenshots
![grafik](https://github.com/bihealth/sodar-server/assets/29800411/a56fc883-32e4-4680-8461-c6cd620fdd81)

![grafik](https://github.com/bihealth/sodar-server/assets/29800411/091a7cc9-5a92-403a-b124-6f7cc564b367)

**Comment by mikkonie** [comment]
It's not broken, it has never been implemented. I haven't been told this is a feature in altamISA nowadays.

If all characteristics and factor values are to be included, this will be a major change. We will have to see about prioritization.

**Comment by sellth** [comment]
Actually, the AltamISA part is wrong. I did not check before, but it seems like AltamISA is not processing these values into lists. So the issue as of now is: adding semicolons using SODAR's own samplesheet editor results in weird code being shown or an uncaught exception during rendering.

**Comment by mikkonie** [comment]
It's not really weird code if the value is unsupported :) The crash should be avoided though. Can you (privately) send me a copy of the samplesheets where such a crash occurs?

**Comment by sellth** [comment]
Altamisa feature request: bihealth/altamisa#140

**Comment by mikkonie** [comment]
Doing this as a part of #2033.

**Comment by mikkonie** [comment]
Done. If I overlooked something or you run into bugs, please open new ticket(s) about it.
