### ISSUE TITLE
Change the default IGV genome from b37 to b37_1kg

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1812]
@holtgrewe informed me that the most recent IGV versions have removed `b37` and `b37_1kg` should be used in its stead.

## Spec

- Replace default genome with `b37_1kg`
- Update existing values in production database
    * Use a migration
- Update release notes in docs
- Once deployed, add admin message advising to update to the newest IGV if warnings are raised

**Comment by mikkonie** [comment]
Done, to be deployed in production tomorrow.

**Comment by xiamaz** [comment]
Hi, all our users in medgen have the issue, that they can't find the b37_1kg genome file. Do you know, where we can find it?

**Comment by holtgrewe** [comment]
@xiamaz Can you install the most recent IGV version?

**Comment by xiamaz** [comment]
IGV `2.16` works. IGV `2.14` doesn't
