### ISSUE TITLE
Support new HPO URL patterns in jax.org

### ISSUE THREAD

**Issue by Nicolai-vKuegelgen** [bihealth/sodar-server#1821]
### Problem

I noticed this announcement on the website of the HPO ontology website:

> We are currently moving our ontology API to [https://ontology.jax.org](https://ontology.jax.org/api/hp/docs/) and expect to fully switch by November 31, 2023 (this date is not firm). Please feel free to use this new API, however term annotation endpoints have not yet been moved.

I assume that could break a few things in Sodar, if no adjustments are made, so this issue is meant as a warning or maybe simply a reminder (I'm also really unsure if this fits bug report of feature request better ...)

### Solution

References to the current API endpoint need to be identified & updated once HPO actually moves their ontology.

**Comment by mikkonie** [comment]
Can you link me to the original announcement? Is there some indication that the ontology will removed from obolibrary.org which we currently link to?

SODAR does not use the API but, instead, imports ontologies locally and uses its own internal Ajax views to search for ontology terems. This saves us the trouble of interfacing with different, potentially unstable APIs.

For term access. we link to obolibrary which is a general repository of ontologies. Unless HPO is removed from obolibrary, this should not affect SODAR.

**Comment by mikkonie** [comment]
Ok, so it appears that:

- Obolibrary now forwards URLs to jax.org, so "pure" old ololibrary URLs still work
- However, bioportal.org doesn't (yet?) support the jax.org URLs
- This results in a 404 in bioportal if the new type of URL is used in the term accession

I need to do a workaround to ensure both old and new URLs work. For now, this can be doable by simply adding `hpo.jax.org` to `SHEETS_ONTOLOGY_URL_SKIP`.

The default accession pattern on the production server should probably be also updated to the new jax.org pattern.
