### ISSUE TITLE
Add bulk downloading for iRODS sample data

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1824]
There has been discussion on enabling bulk downloads of multiple files from iRODS in the SODAR UI.

This was recently discussed in a planning meeting, but not deemed a high-priority task at this time, so marking as `future` for now. Also, this issue is thus more or less a placeholder at the moment.

Requirements and ideas are welcome. I believe @sellth already looked into some potential component to help implement this?

**Comment by sellth** [comment]
Was a reply to #748 

> SODAR could create ZIP files on the fly with this: https://pypi.org/project/stream-zip/
> 
> More info: https://stackoverflow.com/a/70632906

I would still argue strongly for this feature as it removes user dependence on the icommands CLI tools.

**Comment by mikkonie** [comment]
The one issue is that SODAR does not return those files you're downloading via UI, Davrods does. So the zipping feature should have to be implemented there.

**Comment by mikkonie** [comment]
Ah ok, the older issue indeed has more discussion on this, so closing the dupe.
