### ISSUE TITLE
ColumnToggleModal checkboxes not toggled when node group change is triggered

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1849]
### Problem
In the "Toggle Study/Assay column visibility" modal, users can select a "Show all columns of node" box. This toggles visibility for all columns of the node, but the changed status is not reflected by the checkboxes of those columns within the modal.

![grafik](https://github.com/bihealth/sodar-server/assets/29800411/b26a1fee-83b8-4f10-bc96-c1339d10962b)

### Solution
When selecting/deselecting a "Show all" box, all checkboxes of this node automatically change status to reflect the actual visibility status of these columns

**Comment by mikkonie** [comment]
This should happen, it seems to be a bug that the update isn't triggered. I'll get this fixed.

**Comment by mikkonie** [comment]
Fixed. For some reason the bootstrap-vue checkboxes did not register the data change without calling `$forceUpdate()`.
