### ISSUE TITLE
Add generic assay plugin

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1946]
### Problem

Currently linking of the samplesheets metadata to the iRODS data collections is facilitated by assay plugins (assayapps) which perform a pre-defined set of tasks depending on the type of assays we're expecting.

https://sodar-server.readthedocs.io/en/dev/metadata_advanced.html

This means, for every new assay we want to support, a new assay plugin needs to be introduced to the SODAR codebase.  

### Solution

We want to create a new "universal" plugin which takes information from special comments in the `i_Investigation.txt` to define a data linking scheme. This is more flexible than pre-defining one scheme per assay and in-line with the existing "SODAR Assay Plugin" special comment which can be used to overwrite automatic plugin selection.

The logic introduced could potentially be integrated into the main SODAR code and GUI at a later time.

**Comment by mikkonie** [comment]
Done by @sellth, merged.
