### ISSUE TITLE
Add custom ISA-Tab template uploader app

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#1961]
There has been discussion lately about the possibility of uploading custom ISA-Tab templates into SODAR. Currently, templates are hard-coded to being imported from the [cubi-isa-templates](https://github.com/bihealth/cubi-isa-templates) respository. Short of forking SODAR and replacing the dependency with one's own template repository, uploading custom templates is not currently supported.

In the long term, we will probably look into moving away from Cookiecutter templates altogether. However, this is not currently in the roadmap. In the short term, I would propose adding a simple app to upload/manage custom sample sheets. Proposed spec below.

## Spec

- Add admin site app for uploading custom templates
- App provides simple upload form to upload a template as a .zip archive
    * Add some basic "sanity check" file validation to ensure expected files are present
- Save templates into the SODAR database as JSON
- Add list view of existing templates with basic controls
    * Download
    * Delete
    * No replacing/versioning/etc for now, let's keep it simple
- Add Django boolean setting for "use templates from cubi-isa-templates", default True
    * This allows for omitting the CUBI templates if not usable in an organization's projects
- **TBD:** How should this be documented at this point?
    * We should probably list some mandatory requirements etc for the templates
    * Generally this should still be considered an experimental feature in its initial state

With this spec I'd expect this to take some 2-3 days to implement, including testing.

**TBD:** Prioritization/milestone. Comments are welcome.

**Comment by tbrittoborges** [comment]
Just to re-iterate, this feature would be super important for us here in the Heidelberg University Hospital because we're keeping a separate fork for SODAR-SERVER and cubi-isa-templates only to have our own templates. This may be problematic on the long rung.

**Comment by mikkonie** [comment]
Done. This app is still rather rudimentary and doesn't have any in-line editing, REST API or such. Further features can be developed in the future of course and I'm always happy to review pull requests :)

**Comment by tbrittoborges** [comment]
Thank you for providing us with this feature @mikkonie, we will deploy it to our test server and test it.

**Comment by mikkonie** [comment]
> Thank you for providing us with this feature @mikkonie, we will deploy it to our test server and test it.

I hope you'll find it useful @tbrittoborges! It's now also in the latest release v0.15.0 on the main branch. Feel free to open tickets (and possibly submit pull reguests) if you find issues.
