### ISSUE TITLE
Generic assay plugin: Inline links in material columns always point to ResultsReports

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1982]
In this example:
```
Comment[SODAR Assay Link Results]	Standardized Analysis Report
Comment[SODAR Assay Link Row]	Raw Data File;Report File
```

`Raw Data File` columns will link to `Results & Reports` when they should be pointing at the `RowPath`. This behaviour is consistent for all Data and Material headers.

**Comment by sellth** [comment]
There's a check for `target_cols` missing here: https://github.com/bihealth/sodar-server/blob/da733149560ed74dc4dc3d3f5565d9c0418dbc60/samplesheets/assayapps/generic/plugins.py#L66-L72

**Comment by mikkonie** [comment]
Fixed by @sellth, closed.
